### ISSUE TITLE
Tried this out, getting error

### ISSUE THREAD

**Issue by idkjs** [glepnir/jarvim#14]
```sh
❯ jarvim -g                                                                             ─╯
⚠ Backup /Users/mandalarian/.config/nvim to /Users/mandalarian/.config/nvim-bak folder
? What is plugin manage do you use? dein
? What is your Leader Key? Space
? What is your LocalLeader Key? Space
? Choose your favorite colorscheme
? Do you want use dashboard-nvim a better StartScreenPlugin? Yes
? Do you want use spaceline.vim a light and beautiful statusline? Yes
? Do you want use vim-buffet as your bufferline? No
? What is your explorer plugin? nerdtree
? Do you need database plugins? Yes
? Do you want use editorconfig to control program style(like indent,whitespace etc) No
? Choose  your favorite indentline plugin? nathanaelkane/vim-indent-guides
? Do you want to use Caw.vim as comment plugin? No
? Do you want to use vista.vim to view tags and LSP symbols in sidebar No
? Do you want to use vim-gutentags to gen tags No
? Do you want to use vim-quickrun to fast run program in vim? No
? Which Data filetype you need?
? Choose the enhance plugins that you need  rainbow  rainbow parentheses
? Do you want use vim-sandwich more useful than vim-surround? Yes
? Choose the version control plugins that you need tpope/vim-fugitive
? What Languages do you write React
✔ Generate init.vim success
✔ Generate core/core.vim success
✔ Generate dein.vim success
✔ Generate core/general.vim success
✔ Generate core/event.vim success
✔ Generate autoload/initself.vim success
✔ Generate autoload/initself.vim success
✔ Generate bufkill.vim success
✔ Generate difftools.vim success
✔ Generate hlsearch.vim success
✔ Generate nicefold.vim success
✔ Generate whitespace.vim success
✔ Generate plugin folder success
✔ Generate Vim-Devicons success
✔ Generate autoload/theme.vim success
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/glepnir/jarvim/internal/render/dein.(*Dein).GenerateCacheTheme(0x13d49f0, 0x13d49f0, 0x0, 0x0, 0xc00009a1e0)
	/Users/stephen/workstation/jarvis/internal/render/dein/dein.go:56 +0x105
github.com/glepnir/jarvim/internal/logic.RunLogic(0xc0000cdd80, 0x117ba85)
	/Users/stephen/workstation/jarvis/internal/logic/logic.go:41 +0x7bd
github.com/glepnir/jarvim/internal/cli.glob..func1(0x13a1580, 0xc0000989d0, 0x0, 0x1, 0x0, 0x0)
	/Users/stephen/workstation/jarvis/internal/cli/cli.go:31 +0x38
github.com/spf13/cobra.(*Command).execute(0x13a1580, 0xc0000a8050, 0x1, 0x1, 0x13a1580, 0xc0000a8050)
	/Users/stephen/workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x13a1580, 0x1006965, 0xc00008e058, 0x0)
	/Users/stephen/workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/stephen/workspace/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/glepnir/jarvim/internal/cli.Execute()
	/Users/stephen/workstation/jarvis/internal/cli/cli.go:45 +0x31
main.main()
	/Users/stephen/workstation/jarvis/cmd/jarvim/main.go:10 +0x25

 ~                                                            ✘ 2 ╱ 1m 59s ╱ 13:33:02 ─╮
❯
```

Going to try installing go.

**Comment by glepnir** [comment]
sorry for this you need choose a theme

**Comment by idkjs** [comment]
Got it to work. For future reference, which one of the options is theme?

Also, where does the installation script download?

**Comment by idkjs** [comment]
For future reference:
```sh
❯ jarvim -g                                                                                                                                                                         ─╯
⚠ Backup /Users/mandalarian/.config/nvim to /Users/mandalarian/.config/nvim-bak folder
? What is plugin manage do you use? dein
? What is your Leader Key? Space
? What is your LocalLeader Key? Space
? Choose your favorite colorscheme hardcoreplayers/oceanic-material
? Do you want use dashboard-nvim a better StartScreenPlugin? Yes
? Do you want use spaceline.vim a light and beautiful statusline? Yes
? Do you want use vim-buffet as your bufferline? Yes
? What is your explorer plugin? defx.nvim
? Do you need database plugins? Yes
? Do you want use fuzzy find plugin vim-clap? Yes
? Do you want use editorconfig to control program style(like indent,whitespace etc) Yes
? Choose  your favorite indentline plugin? Yggdroot/indentLine
? Do you want to use Caw.vim as comment plugin? Yes
? Do you want to use vista.vim to view tags and LSP symbols in sidebar No
? Do you want to use vim-gutentags to gen tags No
? Do you want to use vim-quickrun to fast run program in vim? No
? Which Data filetype you need? 
? Choose the enhance plugins that you need  vim-floterm  vim terminal float
? Do you want use vim-sandwich more useful than vim-surround? Yes
? Choose the version control plugins that you need 
? What Languages do you write Css, Typescript, Shell, Html, Javascript, React
✔ Generate init.vim success
✔ Generate core/core.vim success
✔ Generate dein.vim success
✔ Generate core/general.vim success
✔ Generate core/event.vim success
✔ Generate autoload/initself.vim success
✔ Generate autoload/initself.vim success
✔ Generate bufkill.vim success
✔ Generate difftools.vim success
✔ Generate hlsearch.vim success
✔ Generate nicefold.vim success
✔ Generate whitespace.vim success
✔ Generate plugin folder success
✔ Generate Vim-Devicons success
✔ Generate autoload/theme.vim success
✔ Generate theme.txt success
✔ Generate Colorscheme success
✔ Generate dashboard-nvim success
✔ Generate Vim-Buffer success
✔ Generate vim-buffer keymap success
✔ Generate Statusline success
✔ Generate Defx.nvim success
✔ Generate defx keymap success
✔ Generate defx keymap success
✔ Generate LoadEnv function success
✔ Generate Database success
✔ Generate database keymap success
✔ Generate vim-clap success
✔ Generate vim-clap keymap success
✔ Generate coc-clap keymap success
✔ Generate editorconfig success
✔ Generate Yggdroot/indentLine success
✔ Generate context_filetype.vim success
✔ Generate Caw.vim success
✔ Generate caw.vim keymap success
⚠ Skip generate Vista.vim cofnig
⚠ Skip generate vista.vim keymap cofnig
⚠ Skip generate vim-gutentags cofnig
⚠ Skip generate vim-quickrun cofnig
⚠ Skip generate quickrun keymap cofnig
✔ Generate dein.vim success
✔ Generate vim-floterm success
✔ Generate vim-flotermkeymap success
✔ Generate vim-sandwich success
✔ Generate vim-sandwich keymap success
✔ Generate textobj plugins success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate textobj vim success
✔ Generate committia.vim success
✔ Generate coc-settings.json file success
✔ Generate vim map success
✔ Generate Css success
✔ Generate Typescript success
✔ Generate Shell success
✔ Generate Html success
✔ Generate Javascript success
✔ Generate React success
✔ Generate autoload coc function success
✔ Generate coc.nvim success
✔ Generate coc.nvim keymap success
✔ Generate Makefile success
✔ Generate install.sh success
```
Install script is in `$HOME/.config/nvim/install.sh`

```
❯ ls ~/.config/nvim/                                                                                                                                                                ─╯
Makefile           autoload/          coc-settings.json  core/              init.vim           install.sh         modules/           plugin/
 
```
then:

run `chmod +x` on `install.sh` then run it.

```sh
❯ chmod +x ~/.config/nvim/install.sh                                                                                                                                                
❯ ~/.config/nvim/install.sh                                                                                                                                                                                                                                                                                                                  
❯ bass ~/.config/nvim/install.sh                                                                                                                                                    

[action]:
 ⇒ Checking node and yarn......
[ok] ===> check pass

[action]:
 ⇒ Install tools...
 ⇒  Found you use mac: 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and codaprotocol/coda).
==> Updated Formulae
Updated 25 formulae.
==> Updated Casks
balenaetcher           clash-for-windows      command-tab-plus       flipper                gns3                   macbreakz              scrutiny               texpad
boost-note             cleanmymac             edex-ui                folx                   insomnia               modern-csv             superproductivity      zerotier-one

==> Downloading https://homebrew.bintray.com/bottles/bat-0.17.1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/2154428e50a347937148312bd787b422fd21b1135b58bf9362aebd3ea08c25d8?response-content-disposition=attachment%3Bfilename%3D%22ba
######################
...
[dein] Update started: (2020/12/04 17:49:02)
[dein] (12/29) [++++++++------------] vim-dadbod
[dein] (13/29) [++++++++------------] spaceline.vim
[dein] (24/29) [++++++++++++++++----] vim-floaterm
[dein] (25/29) [+++++++++++++++++---] vim-devicons
[dein] (28/29) [+++++++++++++++++++-] vim-buffet
[dein] Done: (2020/12/04 17:49:46) ⇒  Clean up...: 
[ok] 
 Congratulations thinkvim install success!!!
 Install your favorite font on here https://www.nerdfonts.com/font-downloads
 If you use linux,you need install ctags with janson support.
 Install the Lsp for your languages.
 Thanks for you love this neovim config.
```

Thanks.

**Comment by glepnir** [comment]
all the plugin and theme cache in `~/.cache/vim`
